version: 2.1

# Reusable YAML chunks
defaults:
  autorebase_filters: &autorebase_filters
    branches:
      ignore:
        - /rebase-pull-request-.*/
        - /cherry-pick-rebase-pull-request-.*/

orbs:
  vfcommon: voiceflow/common@0.0.125
  sonarcloud: sonarsource/sonarcloud@1.0.2

jobs:
  build-and-test:
    executor: vfcommon/default-executor
    steps:
      - checkout
      - vfcommon/install_node_modules
      - vfcommon/lint_source
      - vfcommon/lint_report
      - vfcommon/dependency_tests:
          step_name: Dependency Tests
      - vfcommon/build
      - vfcommon/unit_tests
      - sonarcloud/scan

  release_monorepo:
    executor: vfcommon/node-executor
    parameters:
      install_args:
        description: Additional yarn install command options
        type: string
        default: ""
      sentry_project:
        description: Sentry project to associate the release with
        type: string
        default: ""
      avoid_post_install_scripts:
        description: Skip running post install scripts
        type: boolean
        default: true
      ssh_key:
        description: The SSH key with write permissions to the repository
        type: string
    steps:
      - add_ssh_keys: # To enable write access to repository for removing development environment branches
          fingerprints:
            - << parameters.ssh_key >>
      - checkout
      - vfcommon/install_node_modules:
          install_args: "<< parameters.install_args >>"
          avoid_post_install_scripts: "<< parameters.avoid_post_install_scripts >>"
      - run: |
          git config --global user.email "serviceaccount@voiceflow.com"
          git config --global user.name "Voiceflow"
          SENTRY_PROJECT=<< parameters.sentry_project >> npx lerna@4.0.0 publish --yes --conventional-commits --no-verify-access

workflows:
  test-and-release:
    jobs:
      - build-and-test:
          context: dev-test
          filters:
            <<: *autorebase_filters

      - release_monorepo:
          ssh_key: "94:fb:dc:e2:30:96:9d:61:f5:6f:95:c2:32:20:f7:37"
          context: dev-test
          requires:
            - build-and-test
          filters:
            branches:
              only: master
